version: '3.8'

services:
  # MySQL8服务
  mysql:
    image: mysql:8.0
    container_name: warm_shop_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # 从.env读取
      MYSQL_DATABASE: warm_shop_db                # 项目数据库名
      MYSQL_USER: warm_shop_user                  # 自定义用户
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # 数据持久化
      # 初始化SQL（如有）
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password  # 兼容Python驱动

  # Python后端服务
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: warm_shop_backend
    restart: always
    depends_on:
      - mysql
    environment:
      # 数据库连接配置
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: warm_shop_user
      DB_PASSWORD: ${MYSQL_USER_PASSWORD}
      DB_NAME: warm_shop_db
    ports:
      - "8000:8000"

  # Node前端服务
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: warm_shop_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

# 数据卷（持久化MySQL数据）
volumes:
  mysql_data: