"""
Django settings for warm_shop project.
Generated by 'django-admin startproject' using Django 3.2.23.
"""

import os
from pathlib import Path

# ===================== 兼容 PyMySQL（替换 mysqlclient 时启用） =====================
import pymysql
# 模拟mysqlclient
pymysql.install_as_MySQLdb()
# 移除不兼容的foreign_key_checks参数（加固：先判断是否存在再删除）
conn_init = pymysql.connections.Connection.__init__
if hasattr(conn_init, '__kwdefaults__') and 'foreign_key_checks' in conn_init.__kwdefaults__:
    del conn_init.__kwdefaults__['foreign_key_checks']
# ===================== 基础路径配置 =====================
BASE_DIR = Path(__file__).resolve().parent.parent

# ===================== 安全配置 =====================
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-89$7&z=^%6@8x!09s7^&*()_+lkjhgfdsazxcvbnm')
DEBUG = os.getenv('DJANGO_DEBUG', 'True') == 'True'
ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', '*').split(',')

# ===================== 核心配置：指定自定义用户模型 =====================
AUTH_USER_MODEL = 'users.User'

# ===================== 应用配置 =====================
INSTALLED_APPS = [
    # Django 内置应用
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # 第三方核心应用
    'rest_framework',            # DRF 接口框架
    'rest_framework_simplejwt',  # JWT 认证
    'corsheaders',               # 跨域处理
    #'axes',                      # 登录失败限制
    
    # 自定义应用
    'goods',   # 商品模块
    'users',   # 用户模块
    'carts',   # 购物车模块
    'orders',  # 订单模块
    'payment', # 支付模块
]

# ===================== 中间件配置 =====================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # 跨域中间件（需放在CommonMiddleware前）
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'axes.middleware.AxesMiddleware',  # Axes登录限制中间件
]

ROOT_URLCONF = 'warm_shop.urls'

# ===================== 模板配置 =====================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # 模板目录路径
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'warm_shop.wsgi.application'

# ===================== 数据库配置 =====================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'warm_shop'),
        'USER': os.getenv('DB_USER', 'warm_shop_user'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'ShopUser123!'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',  # 支持emoji等特殊字符
            # 关键修复：移除多语句，仅保留sql_mode配置（pymysql不支持init_command多语句）
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            # 完全删除 foreign_key_checks 相关配置
        },
    }
}
# ===================== 密码验证规则 =====================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', 'OPTIONS': {'min_length': 8}},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ===================== 国际化配置 =====================
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_L10N = True
USE_TZ = False  # 关闭时区转换，适配国内场景

# ===================== 静态/媒体文件配置 =====================
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # 静态文件收集目录
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # 上传文件存储目录

# ===================== 默认主键类型 =====================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ===================== 认证后端配置（解决Axes警告） =====================
AUTHENTICATION_BACKENDS = [
    #'axes.backends.AxesBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# ===================== DRF配置 =====================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '1000/day'
    },
}

# ===================== JWT配置 =====================
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# ===================== CORS跨域配置（优化版） =====================
# 开发环境：允许所有源；生产环境：仅允许指定的可信源（通过环境变量配置）
CORS_ALLOW_ALL_ORIGINS = DEBUG  # 调试模式下允许所有跨域（方便开发）
# 生产环境指定允许的源（通过环境变量 CORS_ALLOWED_ORIGINS 配置，多个用逗号分隔）
CORS_ALLOWED_ORIGINS = []
if not DEBUG:
    allowed_origins = os.getenv('CORS_ALLOWED_ORIGINS', '')
    if allowed_origins:
        CORS_ALLOWED_ORIGINS = allowed_origins.split(',')
        # 生产环境强制关闭全量跨域（防止环境变量配置错误导致安全风险）
        CORS_ALLOW_ALL_ORIGINS = False

# 通用跨域安全配置
CORS_ALLOW_CREDENTIALS = True  # 允许携带cookie
CORS_ALLOW_METHODS = [
    'GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS'
]  # 明确允许的HTTP方法（避免通配符）
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]  # 明确允许的请求头（替代通配符，提升安全性）
CORS_PREFLIGHT_MAX_AGE = 86400  # 预检请求缓存时间（1天），减少OPTIONS请求次数

# ===================== Django-Axes配置 =====================
AXES_ENABLED = True
AXES_FAILURE_LIMIT = 5  # 登录失败5次锁定
AXES_COOLOFF_TIME = 1   # 锁定1小时（单位：小时）
AXES_RESET_ON_SUCCESS = True  # 登录成功后重置失败次数
# 新版Axes核心配置（替代所有废弃项）
AXES_LOCKOUT_CALLABLE = None  # 自定义锁定逻辑（可选）
AXES_USE_CACHE = True         # 使用缓存存储失败记录（默认True）
AXES_CACHE_PREFIX = 'axes:'   # 缓存前缀
# 完全删除以下废弃项：AXES_USE_USER_AGENT、AXES_USE_IP_ADDRESS、AXES_META_PRECEDENCE_ORDER、AXES_ONLY_USER_FAILURES
